# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a119047db5cf8afa309d69c62e19d7fc2757a9a147b2a73cc536f7c7ca1fe9fe6e7d7cc1a84f89f27a432df72861bad16f97c82ae48cbf629ac0ae369876b37
gmail_username: 'funkkymadness@gmail.com'
gmail_password: 'sparkyxz12q'
test:
  secret_key_base: 97304eb3ae8a9068737db00b68e74c82239ee359c7308097105c26b123b7d3055ef08e761bec3848862560247de41b4f1bc368a9320fc1bd8ba36b4222b06d17
gmail_username: 'funkkymadness@gmail.com'
gmail_password: 'sparkyxz12q'
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
gmail_username: 'funkkymadness@gmail.com'
gmail_password: 'sparkyxz12q'